@startuml 操作フロー

|ユーザ|
    :ツールを実行する;
|#AntiqueWhite|ツール|
    :Webサイトを開く;
    :キー入力待ち;
|ブラウザ|
    :認証ポップアップが表示される;
|ユーザ|
    :ユーザー名とパスワードを入力する;
|ブラウザ|
    :Webサイトが表示される;
|ユーザ|
    :ツールのコンソールに任意の文字を入力する;
|ツール|
    :Webサイトを操作する;
|ブラウザ|
    :操作に従う;
|ツール|
    :キー入力待ち;

@enduml